global:
  scrape_interval: 15s 
  evaluation_interval: 15s
  external_labels:
    cluster: 'NTL'
    replica: 'r1'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: 
          - 'prometheus1:9001'
          - 'prometheus2:9002'
          - 'prometheus3:9003'
          - 'prometheus4:9004'
          - 'prometheus_remote:9005'

  - job_name: 'thanos'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'thanos_sidecar1:10912'
          - 'thanos_sidecar2:10922'
          - 'thanos_sidecar3:10932'
          - 'thanos_sidecar4:10942'
          - 'thanos_query1:10914'
          - 'thanos_query2:10924'
          - 'thanos_query3:10934'
          - 'thanos_query4:10944'
          - 'thanos_query_frontend1:19091'
          - 'thanos_query_frontend2:19092'
          - 'thanos_query_frontend3:19093'
          - 'thanos_query_frontend4:19094'
          - 'thanos_store1:10916'
          - 'thanos_store2:10926'
          - 'thanos_compactor:10902'
          - 'thanos_ruler:10904'
          - 'thanos_bucket_web:10905'
          - 'thanos_receive:10952'

  - job_name: 'minio'
    scrape_interval: 5s
    static_configs:
      - targets: 
          - 'minio:9000'
    metrics_path: /minio/prometheus/metrics

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'cadvisor:8080'

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'node_exporter:9100'
