telegram_token: "1711098472:AAF1DKMfaB1ljAWzxl2FMy-sL_Cx7mu7CGE"
template_path: "/etc/telegrambot/template.tmpl"
time_zone: "Asia/Ho_Chi_Minh"
split_token: "|"
time_outdata: "02/01/2006 15:04:05"
split_msg_byte: 10000